# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  firebase_credentials_file = File.expand_path("../secrets/firebase-app-distribution.json", __dir__)

  private_lane :increment_android_version_code do
    version_file = File.expand_path("../version.properties", __dir__)
    version_properties = {}

    File.foreach(version_file) do |line|
      key, value = line.strip.split("=", 2)
      next if key.nil? || value.nil?

      version_properties[key] = value
    end

    current_version_code = version_properties.fetch("VERSION_CODE").to_i
    next_version_code = current_version_code + 1
    version_properties["VERSION_CODE"] = next_version_code.to_s

    File.write(
      version_file,
      version_properties.map { |key, value| "#{key}=#{value}" }.join("\n") + "\n"
    )

    UI.message("VERSION_CODE bumped: #{current_version_code} -> #{next_version_code}")
    next_version_code
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Internal testing build distributed via Firebase App Distribution (Debug)"
  lane :internal_test do
    increment_android_version_code

    gradle(
      task: "assemble",
      build_type: "Debug"
    )

    firebase_app_distribution(
      app: "1:425817050266:android:655301002c0bc7c666a323",
      android_artifact_type: "APK",
      android_artifact_path: "app/build/outputs/apk/debug/app-debug.apk",
      groups: "tester",
      release_notes: "Internal debug build",
      service_credentials_file: firebase_credentials_file
    )
  end

  desc "Beta build distributed via Firebase App Distribution (Release)"
  lane :beta do
    increment_android_version_code

    gradle(
      task: "bundle",
      build_type: "Release"
    )

    firebase_app_distribution(
      app: "1:425817050266:android:655301002c0bc7c666a323",
      android_artifact_type: "AAB",
      android_artifact_path: "app/build/outputs/bundle/release/app-release.aab",
      groups: "tester",
      release_notes: "Beta build",
      service_credentials_file: firebase_credentials_file
    )
  end

  desc "Release build uploaded to Google Play"
  lane :deploy do
    increment_android_version_code

    gradle(
      task: "bundle",
      build_type: "Release"
    )

    upload_to_play_store(
      aab: "app/build/outputs/bundle/release/app-release.aab",
      track: "production",
      skip_upload_apk: true
    )
  end
end
